---
- name: Set OS-specific variables
  ansible.builtin.set_fact:
    docker_host_env: "{{ os_config[ansible_system].docker_host_env }}"
    duckdns_updater_directory: "{{ os_config[ansible_system].duckdns_updater_directory }}"
    become_enabled: "{{ os_config[ansible_system].become_enabled }}"
  vars:
    os_config:
      Darwin:
        docker_host_env: "unix:///Users/{{ ansible_user_id }}/.colima/default/docker.sock"
        duckdns_updater_directory: "{{ ansible_user_dir }}/Library/Application Support/DuckDNS Updater"
        become_enabled: false
      Linux:
        docker_host_env: "unix:///var/run/docker.sock"
        duckdns_updater_directory: "/var/lib/duckdns_updater"
        become_enabled: true
  tags: unix

- name: Ensure Docker exists
  ansible.builtin.include_role:
    name: docker
  tags: unix

- name: Ensure DuckDNS Updater directories exist
  ansible.builtin.file:
    path: "{{ item }}" # Iterates through the list of paths
    state: directory
    mode: '0755'
  loop:
    - "{{ duckdns_updater_directory }}"
    - "{{ duckdns_updater_directory }}/config"
  become: "{{ become_enabled }}"
  tags: unix

- name: Ensure DuckDNS Updater Docker container is running and configured
  community.docker.docker_container:
    name: duckdns
    image: lscr.io/linuxserver/duckdns:latest
    state: started
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "{{ duckdns_updater_directory }}/config:/config"
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "{{ timezone }}"
      TOKEN: "{{ duckdns_token }}"
      UPDATE_IP: "ipv4"
      LOG_FILE: "false"
      SUBDOMAINS: "{{ duckdns_subdomains | join(',') }}"
  become: "{{ become_enabled }}"
  environment:
    # Conditionally set DOCKER_HOST for macOS (Colima).
    # This environment variable will only be effective on macOS hosts when become_enabled_for_os is true.
    # On Linux, this variable is generally not needed as Docker client defaults to /var/run/docker.sock.
    DOCKER_HOST: "{{ docker_host_env }}" # Use 'omit' to not set it on Linux
  tags: unix
