---
- name: Check if Rust is installed
  ansible.builtin.command: rustc --version
  register: rust_check
  changed_when: false
  failed_when: false
  ignore_errors: true
  tags: unix

# Install rustup using Homebrew if Rust is not installed
- name: Install rustup
  community.general.homebrew:
    name: rustup
    state: present
  become: false
  when: rust_check.rc != 0
  tags: macos

# Run rustup to install Rust if not installed
- name: Install Rust using rustup
  ansible.builtin.command: rustup-init -y
  args:
    creates: ~/.cargo/bin/rustc
  when: rust_check.rc != 0
  tags: unix

# Ensure the environment variables are set for Rust
- name: Ensure Cargo bin directory is in PATH
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    line: 'export PATH="$HOME/.cargo/bin:$PATH" # rust'
    insertbefore: "^{{ custom_config_end_delimiter }}"
    state: present
  notify: Reload shell
  tags: unix
