---
- name: Ensure Homebrew is installed
  ansible.builtin.stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_installed
  failed_when: false
  changed_when: false
  ignore_errors: true
  become: false
  when: ansible_system == "Darwin"
  tags: dev, macos

- name: Install Homebrew if the package manager is not installed
  ansible.builtin.shell: >
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  become: false
  when:
    - ansible_os_family == "Darwin"
    - not homebrew_installed.stat.exists
  changed_when: false
  tags: dev, macos

- name: Ensure .zshrc includes Homebrew path for Apple Silicon-based machine
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    line: "export PATH=/opt/homebrew/bin:$PATH # brew"
    state: present
    create: yes
    insertafter: "^{{ custom_config_start_delimiter }}"
    mode: "0644"
  become: false
  notify: Reload shell
  when:
    - ansible_os_family == "Darwin"
  tags: dev, macos
