- name: Ensure zsh is installed
  ansible.builtin.homebrew:
    name: zsh
    state: present
  become: false

- name: Ensure zsh is in /etc/shells
  ansible.builtin.shell: |
    if ! grep -q "/opt/homebrew/bin/zsh" /etc/shells; then
      echo "/opt/homebrew/bin/zsh" | sudo tee -a /etc/shells
    fi
  become: true
  changed_when: false

- name: Change default shell to zsh
  ansible.builtin.shell: chsh -s $(which zsh)
  become: true
  changed_when: false
