---
- name: Ensure Android Command Line Tools in macOS
  community.general.homebrew_cask:
    name: android-commandlinetools
    state: present
  when: ansible_os_family == "Darwin"
  become: false
  tags: macos

- name: Make adb available
  ansible.builtin.command: sdkmanager --install "platform-tools"
  args:
    stdin: "y"
  changed_when: false
  become: false
  tags: unix

- name: Make Android tools available
  ansible.builtin.command: |
    sdkmanager --install \
      "platform-tools" \
      "platforms;android-34" \
      "build-tools;34.0.0" \
      "system-images;android-34;google_atd;arm64-v8a"
  args:
    stdin: "y"
  changed_when: false
  become: false
  tags: unix

- name: Agree on Android licenses
  ansible.builtin.shell: |
    sdkmanager --licenses <<EOF
    y
    y
    y
    y
    y
    y
    EOF
  changed_when: false
  become: false
  tags: unix
