---
- name: Check if Kotlin plugin is already added
  ansible.builtin.command: asdf plugin list
  register: plugin_list
  changed_when: false
  failed_when: false
  become: false
  tags: unix

- name: Add Kotlin plugin if not already added
  ansible.builtin.command: asdf plugin add kotlin https://github.com/asdf-community/asdf-kotlin.git
  when: "'kotlin' not in plugin_list.stdout"
  register: plugin_added
  changed_when: plugin_added.rc == 0
  become: false
  tags: unix

- name: Check if Kotlin is already installed
  ansible.builtin.command: asdf list kotlin
  register: kotlin_list
  failed_when: false
  changed_when: false
  tags: unix

- name: Get the latest version of Kotlin
  ansible.builtin.command: asdf latest kotlin
  register: kotlin_latest
  changed_when: false
  tags: unix

- name: Install latest version of Kotlin if not already installed
  ansible.builtin.command: asdf install kotlin {{ kotlin_latest.stdout }}
  when: kotlin_latest.stdout not in kotlin_list.stdout
  register: kotlin_install
  failed_when: "'already installed' not in kotlin_install.stdout and kotlin_install.rc != 0"
  changed_when: kotlin_install.rc == 0
  tags: unix

- name: Set global Kotlin version
  ansible.builtin.command: asdf global kotlin {{ kotlin_latest.stdout }}
  when: kotlin_latest.stdout not in kotlin_list.stdout
  changed_when: kotlin_install.changed
  become: false
  tags: unix
