---
exclude_paths:
  - .git/
  - .github/
  - roles/git/vars/main.yml
  - group_vars/dev/gpg.yml

warn_list:
  - package-latest
  - yaml
  - fqcn
  - experimental
  - name[template]
  - no-handler
  - command-instead-of-shell

skip_list:
  - args[module]
