---
- name: "Set up macOS environment"
  hosts: all
  roles:
    - role: package_manager
      become: false
    - role: zsh
      become: true
    - role: packages
      become: false
    - role: gpg
      become: false
    - role: git
      become: false
    - role: starship
      become: false
    - role: tmux
      become: false
    - role: helix
      become: false
    - role: android_sdk
      become: false
    - role: vscode
      become: false
    - role: aerospace
      become: false
    - role: alacritty
      become: false
    - role: os_settings
      become: true
    - role: languages
      become: false
