---
- name: Configure ubuntu server
  hosts: home_lab
  tasks:
    # - name: Configure docker
    #   ansible.builtin.include_role:
    #     name: docker
    #   tags: server, debian

    - name: Configure zsh
      ansible.builtin.include_role:
        name: zsh
      tags: server, debian
