---
- name: "Set up macOS environment"
  hosts: macos
  tasks:
    - name: Configure OS settings
      ansible.builtin.include_role:
        name: os_settings
      tags: dev, macos

    - name: Configure Package Manager
      ansible.builtin.include_role:
        name: package_manager
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure zsh settings
      ansible.builtin.include_role:
        name: zsh
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure gpg settings
      ansible.builtin.include_role:
        name: gpg
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure git settings
      ansible.builtin.include_role:
        name: git
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure starship settings
      ansible.builtin.include_role:
        name: starship
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure tmux settings
      ansible.builtin.include_role:
        name: tmux
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure helix settings
      ansible.builtin.include_role:
        name: helix
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure yazi settings
      ansible.builtin.include_role:
        name: yazi
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure WezTerm settings
      ansible.builtin.include_role:
        name: wezterm
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure vscode settings
      ansible.builtin.include_role:
        name: vscode
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure Language Manager settings
      ansible.builtin.include_role:
        name: language_manager
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure direnv settings
      ansible.builtin.include_role:
        name: direnv
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure rust settings
      ansible.builtin.include_role:
        name: rust
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure java settings
      ansible.builtin.include_role:
        name: java
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure kotlin settings
      ansible.builtin.include_role:
        name: kotlin
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure android settings
      ansible.builtin.include_role:
        name: android
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure flutter settings
      ansible.builtin.include_role:
        name: flutter
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure packages settings
      ansible.builtin.include_role:
        name: packages
      tags: dev, macos

    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers

    - name: Configure ios settings
      ansible.builtin.include_role:
        name: ios
      tags: dev, macos

  handlers:
    - name: Reload shell
      ansible.builtin.command: "zsh -c \"source {{ home_path }}/.zshrc\""
      failed_when: false
      changed_when: false
      ignore_errors: false
