---
- name: "Try Ubuntu Lab"
  hosts: home_lab
  tasks:
    - name: Hello world
      ansible.builtin.command: "echo \"Hello world!\""
      failed_when: false
      changed_when: false
      ignore_errors: false
