---
- name: Ensure the package manager is installed
  ansible.builtin.include_role:
    name: package_manager
  tags: dev, macos

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: false
  when: ansible_os_family == "Darwin"
  become: false
  tags: dev, macos

- name: Install Homebrew packages
  community.general.homebrew:
    state: present
    name: "{{ packages_common_packages + packages_mac_only_packages }}"
    upgrade_all: false
  become: false
  tags: dev, macos

- name: Install Homebrew cask packages
  community.general.homebrew_cask:
    state: present
    name: "{{ packages_mac_gui_packages }}"
    upgrade_all: false
  become: false
  tags: dev, macos

- name: Install Homebrew mas packages
  community.general.mas:
    state: present
    id: "{{ packages_mac_gui_app_store_packages }}"
    upgrade_all: false
  become: false
  tags: dev, macos
