---
- name: Install packages on macOS
  ansible.builtin.include_tasks: macos.yml
  when: ansible_os_family == "Darwin"
  become: false
  tags: macos

- name: Install packages on Debian-based Linux
  ansible.builtin.include_tasks: macos.yml
  when: ansible_facts['os_family'] == 'Debian'
  become: false
  tags: debian
