- name: Install homebrew
  include_role:
    name: geerlingguy.mac.homebrew

- name: Make sure homebrew bin is in path
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: '/opt/homebrew/bin'
  become: true
  become_user: root

- name: Update packages
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

# - name: Install essential packages
#   community.general.homebrew:
#     name: "{{ packages }}"
#     state: latest

- name: Disable SSH password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Restart SSH daemon
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed
