---
- name: Ensure Helix in macOS
  ansible.builtin.include_tasks: macos.yml
  when: ansible_os_family == "Darwin"
  tags: macos

- name: Link directory from role files to local destination
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ dotfiles_directory_path }}/helix"
    state: link
    mode: "0755"
    force: true
    follow: false
  become: false
  tags: unix

- name: Add aliases in zsh configuration
  ansible.builtin.lineinfile:
    path: "{{ dotfiles_directory_path }}/zsh/aliases.zsh"
    line: alias vi='hx'
    insertbefore: "^{{ custom_config_end_delimiter }}"
    state: present
  notify: Reload shell
  become: false
  tags: unix

- name: Add configurations in zsh configuration
  ansible.builtin.lineinfile:
    path: "{{ dotfiles_directory_path }}/zsh/configs.zsh"
    line: export VISUAL=hx
    insertbefore: "^{{ custom_config_end_delimiter }}"
    state: present
  notify: Reload shell
  become: false
  tags: unix

- name: Add configurations in zsh configuration
  ansible.builtin.lineinfile:
    path: "{{ dotfiles_directory_path }}/zsh/configs.zsh"
    line: export EDITOR=hx
    insertbefore: "^{{ custom_config_end_delimiter }}"
    state: present
  notify: Reload shell
  become: false
  tags: unix
