---
- name: Ensure helix in macOS
  ansible.builtin.include_tasks: macos/install.yml
  when: ansible_os_family == "Darwin"
  tags: macos

- name: Ensure helix in debian
  ansible.builtin.include_tasks: debian/install.yml
  when: ansible_os_family == "Debian"
  tags: debian

- name: Link directory from role files to local destination when local
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ dotfiles_directory_path }}/helix"
    state: link
    mode: "0755"
    force: true
    follow: false
  when: is_local_connection
  become: false
  tags: unix

- name: Copy directory from role files to local destination when not local
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: "{{ dotfiles_directory_path }}/helix/"
    mode: "0644"
    force: true
  when: not is_local_connection
  become: false
  tags: unix

- name: Add aliases in zsh configuration
  ansible.builtin.lineinfile:
    path: "{{ dotfiles_directory_path }}/zsh/aliases.zsh"
    line: alias vi='hx'
    insertbefore: "^{{ custom_config_end_delimiter }}"
    state: present
  become: false
  tags: unix

- name: Add configurations in zsh configuration
  ansible.builtin.lineinfile:
    path: "{{ dotfiles_directory_path }}/zsh/configs.zsh"
    line: export VISUAL=hx
    insertbefore: "^{{ custom_config_end_delimiter }}"
    state: present
  become: false
  tags: unix

- name: Add configurations in zsh configuration
  ansible.builtin.lineinfile:
    path: "{{ dotfiles_directory_path }}/zsh/configs.zsh"
    line: export EDITOR=hx
    insertbefore: "^{{ custom_config_end_delimiter }}"
    state: present
  become: false
  tags: unix
