---
- name: Ensure VSCode in macOS
  community.general.homebrew_cask:
    state: present
    name: visual-studio-code
  become: false
  tags: macos

- name: Ensure destination directory exists
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User"
    state: directory
    mode: 0755
  become: false
  tags: unix

- name: Link settings from role files to local destination
  ansible.builtin.file:
    src: "{{ role_path }}/files/settings.json"
    dest: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/settings.json"
    state: link
    mode: 0644
    force: true
    follow: false
  become: false
  when: ansible_os_family == "Darwin"
  tags: macos

- name: Link keybindings from role files to local destination
  ansible.builtin.file:
    src: "{{ role_path }}/files/keybindings.json"
    dest: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/keybindings.json"
    state: link
    mode: 0644
    force: true
    follow: false
  become: false
  when: ansible_os_family == "Darwin"
  tags: macos

- name: Link snippets from role files to local destination
  ansible.builtin.file:
    src: "{{ role_path }}/files/snippets"
    dest: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/snippets"
    state: link
    mode: 0644
    force: true
    follow: false
  become: false
  when: ansible_os_family == "Darwin"
  tags: macos
