---
- name: Ensure VSCode in macOS
  ansible.builtin.include_tasks: macos.yml
  when: ansible_os_family == "Darwin"
  tags: macos

- name: Link settings from role files to local destination
  ansible.builtin.file:
    src: "{{ role_path }}/files/settings.json"
    dest: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/settings.json"
    state: link
    mode: "0644"
    force: true
    follow: false
  become: false
  when: ansible_os_family == "Darwin"
  tags: macos

- name: Link keybindings from role files to local destination
  ansible.builtin.file:
    src: "{{ role_path }}/files/keybindings.json"
    dest: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/keybindings.json"
    state: link
    mode: "0644"
    force: true
    follow: false
  become: false
  when: ansible_os_family == "Darwin"
  tags: macos

- name: Link snippets from role files to local destination
  ansible.builtin.file:
    src: "{{ role_path }}/files/snippets"
    dest: "{{ lookup('env', 'HOME') }}/Library/Application Support/Code/User/snippets"
    state: link
    mode: "0644"
    force: true
    follow: false
  become: false
  when: ansible_os_family == "Darwin"
  tags: macos
