---
- name: Check if Direnv plugin is already added
  ansible.builtin.command: asdf plugin list
  register: plugin_list
  changed_when: false
  failed_when: false
  become: false
  tags: unix

- name: Add Direnv plugin if not already added
  ansible.builtin.command: asdf plugin add direnv
  when: "'direnv' not in plugin_list.stdout"
  register: plugin_added
  changed_when: plugin_added.rc == 0
  become: false
  tags: unix

- name: Set direnv configuration in zsh
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    block: |
      eval "$(direnv hook zsh)"
      source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"
    marker: "# {mark} direnv"
    state: present
    create: yes
    mode: "0644"
    insertbefore: "^{{ custom_config_end_delimiter }}"
  become: false
  when: ansible_env.SHELL | basename == "zsh"
  notify: Reload shell
  tags: unix

- name: Configure direnv
  ansible.builtin.command: asdf direnv setup --shell zsh --version latest
  changed_when: true
  failed_when: false
  when:
    - "'direnv' not in plugin_list.stdout"
    - plugin_added.rc == 0
  become: false
  tags: unix
