---
- name: Check if Direnv plugin is already added
  ansible.builtin.command: asdf plugin list
  register: plugin_list
  changed_when: false
  failed_when: false
  become: false
  tags: unix

- name: Add Direnv plugin if not already added
  ansible.builtin.command: asdf plugin add direnv
  when: "'direnv' not in plugin_list.stdout"
  register: plugin_added
  changed_when: plugin_added.rc == 0
  become: false
  notify: Configure direnv
  tags: unix
