---
- name: Ensure direnv in macOS
  ansible.builtin.include_tasks: macos.yml
  tags: macos

- name: Ensure .zshrc exists
  ansible.builtin.file:
    path: "{{ home_path }}/.zshrc"
    state: touch
    mode: "0644"
  tags: unix

- name: Ensure .zshrc includes direnv initialization
  ansible.builtin.blockinfile:
    path: "{{ home_path }}/.zshrc"
    block: 'eval "$(direnv hook zsh)"'
    state: present
    mode: "0644"
    insertbefore: "^{{ custom_config_end_delimiter }}"
    marker: "# --- {mark} direnv ---"
  become: false
  notify: Reload shell
  when: ansible_env.SHELL is search("zsh")
  tags: unix
