---
- name: Ensure target options directory exists for {{ current_android_studio_dir.path }}
  ansible.builtin.file:
    path: "{{ current_android_studio_dir.path }}/{{ common_options_subdir }}"
    state: directory
    mode: "0755" # 적절한 권한 설정
    owner: "{{ ansible_user_id }}" # 현재 사용자 소유로 설정 (macOS 환경에서 중요)
    group: "{{ ansible_user_gid }}"
  when: current_android_studio_dir.path is defined
  tags: unix

- name: Ensure target keymaps directory exists for {{ current_android_studio_dir.path }}
  ansible.builtin.file:
    path: "{{ current_android_studio_dir.path }}/{{ common_keymaps_subdir }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  when: current_android_studio_dir.path is defined
  tags: unix

- name: Link static Android Studio option files
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ current_android_studio_dir.path }}/{{ common_options_subdir }}/{{ item.path | basename }}"
    state: link
    force: yes
  loop: "{{ static_config_files_options.files }}"
  loop_control:
    label: "Linking option file {{ item.path | basename }}"
  tags: unix

- name: Link static Android Studio keymaps files
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ current_android_studio_dir.path }}/{{ common_keymaps_subdir }}/{{ item.path | basename }}"
    state: link
    force: yes
  loop: "{{ static_config_files_keymaps.files }}"
  loop_control:
    label: "Linking keymap file {{ item.path | basename }}"
  tags: unix

- name: Create or update dynamic Android Studio config file (android.sdk.path.xml)
  ansible.builtin.template:
    src: "options/android.sdk.path.xml.j2"
    dest: "{{ current_android_studio_dir.path }}/{{ common_options_subdir }}/android.sdk.path.xml"
    mode: "0644"
  when: android_sdk_root is defined
  tags: unix

- name: Define Android Studio plugins to install
  ansible.builtin.set_fact:
    android_studio_plugins:
      - id: "tanned.grazi"
        dir_name: "grazi" # 예상되는 플러그인 설치 디렉터리 이름 (소문자, 공백 없음)
      - id: "IdeaVim"
        dir_name: "ideavim"
      - id: "com.seventh7.plugin.rainbowbrackets"
        dir_name: "rainbowbrackets"
      - id: "me.artspb.irefactor.indentrainbow"
        dir_name: "indentrainbow"
  tags: unix

- name: Include tasks to install Android Studio plugins
  ansible.builtin.include_tasks: install_plugins.yml
  loop: "{{ android_studio_plugins }}"
  loop_control:
    loop_var: current_plugin # 중요: 이 변수로 하위 태스크에 전달됩니다.
    label: "Installing plugin: {{ current_plugin.id }}"
  tags: unix
