---
- name: Check if Node.js plugin is already added
  ansible.builtin.command: asdf plugin list
  register: plugin_list
  changed_when: false
  failed_when: false
  become: false
  tags: unix

- name: Add Node.js plugin if not already added
  ansible.builtin.command: asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  when: "'nodejs' not in plugin_list.stdout"
  register: plugin_added
  changed_when: plugin_added.rc == 0
  become: false
  tags: unix

- name: Check if Node.js is already installed
  ansible.builtin.command: asdf list nodejs
  register: nodejs_list
  failed_when: false
  changed_when: false
  tags: unix

- name: Install 22 version of Node.js if not already installed
  ansible.builtin.command: asdf install nodejs {{ nodejs_version }}
  when: "nodejs_version not in nodejs_list.stdout"
  register: nodejs_install
  failed_when: "'already installed' not in nodejs_install.stdout and nodejs_install.rc != 0"
  changed_when: nodejs_install.rc == 0
  tags: unix

- name: Set global Node.js version
  ansible.builtin.command: asdf set nodejs {{ nodejs_version }}
  args:
    chdir: "{{ ansible_env.HOME }}"
  when: "nodejs_version not in nodejs_list.stdout"
  changed_when: nodejs_install.changed
  become: false
  tags: unix
