---
- name: Update packages
  ansible.builtin.apt:
    update_cache: yes
  become: true
  tags: debian

- name: Install required packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
  become: true
  tags: debian

- name: Create directory /etc/apt/keyrings with appropriate permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true
  tags: debian

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  become: true
  tags: debian

- name: Add Docker repository to sources.list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: true
  tags: debian

- name: Update packages after adding the Docker repository
  ansible.builtin.apt:
    update_cache: yes
  become: true
  tags: debian

- name: Install docker-related packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true
  tags: debian
