---
template_config_delimiter: "# TEMPLATE CONFIG"
custom_config_start_delimiter: "# START CUSTOM CONFIG"
custom_config_end_delimiter: "# END CUSTOM CONFIG"

is_local_connection: "{{ ansible_connection == 'local' }}"
