---
- name: Ensure Xcode license is accepted
  ansible.builtin.command: xcodebuild -license accept
  when: ansible_os_family == "Darwin"
  register: xcode_license_check
  changed_when: false
  become: true
  tags: macos

- name: Ensure package manager is installed
  community.general.homebrew:
    state: present
    name: cocoapods
  become: false
  when: ansible_os_family == "Darwin"
  notify: Install simulator runtime
  tags: macos


# Format on save
# https://stackoverflow.com/questions/26993977/how-to-use-code-formatter-in-xcode-for-swift
# https://stackoverflow.com/questions/5975026/xcode-4-idekeybindings-multiple-commands-for-one-keystroke

# vim mode
# KeyBindingsMode = "Vi"

# theme
# XCFontAndColorCurrentDarkTheme = "Github (Dark).xccolortheme";
# XCFontAndColorCurrentLightTheme = "Github (Light).xccolortheme";
# XCFontAndColorCurrentTheme = "Github (Dark).xccolortheme";
