---
- name: Ensure Aerospace is installed
  community.general.homebrew_cask:
    state: present
    name: nikitabobko/tap/aerospace
  become: false
  tags: macos

- name: Ensure destination directory exists
  ansible.builtin.file:
    path: "{{ dotfiles_directory_path }}/aerospace"
    state: directory
    mode: "0755"
  become: false
  tags: macos

- name: Link file from role files to local destination
  ansible.builtin.file:
    src: "{{ role_path }}/files/config.toml"
    dest: "{{ dotfiles_directory_path }}/aerospace/aerospace.toml"
    state: link
    mode: "0644"
    force: true
    follow: false
  become: false
  tags: macos
