---
all:
  children:
    dev:
      hosts:
        macos:
          ansible_connection: local

    server:
      hosts:
        home_lab:
          ansible_connection: ssh
          ansible_host: 192.168.219.108
          ansible_user: youngmin-ubuntu
          ansible_ssh_private_key_file: /Users/youngmin/.ssh/github
