---
- name: Check if zigbee2mqtt directory exists
  ansible.builtin.stat:
    path: "{{ zigbee2mqtt_directory }}"
  register: zigbee2mqtt_dir_stat
  tags: unix

- name: Clone zigbee2mqtt repo if the directory does not exist
  ansible.builtin.git:
    repo: "https://github.com/Koenkk/zigbee2mqtt.git"
    dest: "{{ zigbee2mqtt_directory }}"
    version: 2.6.0
  when: not zigbee2mqtt_dir_stat.stat.exists
  tags: unix

- name: Check for USB devices
  ansible.builtin.shell: "ls /dev/tty.usb*"
  register: usb_devices_result
  changed_when: false
  failed_when: usb_devices_result.rc != 0 or usb_devices_result.stdout_lines | length == 0
  tags: macos

- name: Set fact with the first USB device path
  ansible.builtin.set_fact:
    usb_device_path: "{{ usb_devices_result.stdout_lines[0] }}"
  tags: unix

- name: Check if the configuration file exists
  ansible.builtin.stat:
    path: "{{ zigbee2mqtt_directory }}/data/configuration.yaml"
  register: config_file
  tags: unix

- name: Render Zigbee2MQTT configuration file if not exists
  ansible.builtin.template:
    src: "config.yaml.j2"
    dest: "{{ zigbee2mqtt_directory }}/data/configuration.yaml"
    mode: "0644"
  tags: unix
  when: not config_file.stat.exists

- name: Ensure Node.js exists
  ansible.builtin.include_role:
    name: nodejs
  tags: unix

- name: Get node executable path
  ansible.builtin.command: which node
  register: node_path_result
  failed_when: false
  changed_when: false
  tags: unix

- name: Set node fact
  ansible.builtin.set_fact:
    node_path: "{{ node_path_result.stdout }}"
  tags: unix

- name: Install Node.js packages for zigbee2mqtt
  community.general.pnpm:
    path: "{{ zigbee2mqtt_directory }}"
    state: latest
  tags: unix

- name: Create a launchd service file
  ansible.builtin.template:
    src: z2m.plist.j2
    dest: "{{ zigbee2mqtt_service_manager_file }}"
    mode: "0644"
  tags: macos

- name: Run launchd
  community.general.launchd:
    name: "{{ zigbee2mqtt_service_name }}"
    state: restarted
  tags: macos
