---
- name: Set OS-specific variables
  ansible.builtin.set_fact:
    zigbee2mqtt_service_name: "{{ os_config[ansible_system].zigbee2mqtt_service_name }}"
    zigbee2mqtt_directory: "{{ os_config[ansible_system].zigbee2mqtt_directory }}"
    zigbee2mqtt_service_manager_file: "{{ os_config[ansible_system].zigbee2mqtt_service_manager_directory }}/{{ os_config[ansible_system].zigbee2mqtt_service_name }}.{{ os_config[ansible_system].file_format }}"
  vars:
    os_config:
      Darwin:
        zigbee2mqtt_directory: "{{ ansible_user_dir }}/src/zigbee2mqtt"
        zigbee2mqtt_service_manager_directory: "{{ ansible_user_dir }}/Library/LaunchAgents"
        zigbee2mqtt_service_name: "io.zigbee2mqtt"
        file_format: "plist"
      Linux:
        zigbee2mqtt_directory: "{{ ansible_user_dir }}/src/zigbee2mqtt"
        zigbee2mqtt_service_manager_directory: "/etc/systemd/system"
        zigbee2mqtt_service_name: "zigbee2mqtt"
        file_format: "service"
  tags: unix

- name: Configure zigbee2mQtt on macOS
  ansible.builtin.include_tasks: macos.yml
  when: ansible_os_family == "Darwin"
  tags: macos
