---
- name: Ensure zsh on macOS
  ansible.builtin.include_tasks: macos/dotfile.yml
  when: ansible_system == "Darwin"
  tags: macos

- name: Ensure zsh on Debian-based Linux
  ansible.builtin.include_tasks: debian/dotfile.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags: debian

- name: Set the $DOTFILES path in zsh
  ansible.builtin.set_fact:
    dotfiles_zsh_path: "{{ role_path }}/files"
  tags: unix

- name: Generate .zshrc from template
  ansible.builtin.template:
    src: "zshrc.j2"
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    mode: 0664
  notify: Reload shell
  tags: unix

- name: Ensure .zshrc includes Homebrew path for Apple Silicon-based machine
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    line: "export PATH=/opt/homebrew/bin:$PATH # brew"
    state: present
    create: yes
    insertafter: "^{{ custom_config_start_delimiter }}"
    mode: 0644
  become: false
  notify: Reload shell
  when:
    - ansible_os_family == "Darwin"
    - ansible_facts['pkg_mgr'] == 'homebrew'
  tags: macos

- name: Reload shell
  ansible.builtin.command: "zsh -c \"source {{ lookup('env', 'HOME') }}/.zshrc\""
  failed_when: false
  changed_when: false
  ignore_errors: false
