---
packages_common_packages:
  - gnupg
  - coreutils
  - curl
  - wget
  - bash-language-server
  - entr
  - ffmpeg
  - fzf
  - lcov
  - llvm
  - ncdu
  - fastfetch
  - protobuf
  - shellcheck
  - tldr
  - tree
  - lsd
  - zellij
  - ghostscript
  - imagemagick

packages_mac_only_packages:
  - awk
  - starship
  - gitmoji
  - marksman
  - mas
  - cocoapods
  - qemu
  - docker
  - colima
  - xcodesorg/made/xcodes
  - mermaid-cli
  - chafa
  - bufbuild/buf/buf
  - fop
  - unixodbc

packages_mac_gui_packages:
  - google-chrome
  - keka
  - openinterminal
  - raycast
  - antigravity
  - antigravity-ide
  - antigravity-cli
  - codex
  - claude-code
  - font-jetbrains-mono-nerd-font
  - swiftformat-for-xcode
  - rustdesk
  - claude

packages_mac_gui_app_store_packages:
  - 899247664 # TestFlight
  - 1450874784 # Transporter
  - 937984704 # Amphetamine
  - 1437138382 # WhatFont

packages_debian_gui_packages:
  - google-chrome-stable
  - code
