---
- name: Ensure ripgrep in macOS
  ansible.builtin.include_tasks: macos/install.yml
  when: ansible_os_family == "Darwin"
  tags: macos

- name: Ensure ripgrep in debian
  ansible.builtin.include_tasks: debian/install.yml
  when: ansible_os_family == "Debian"
  tags: debian

- name: Add aliases in zsh configuration
  ansible.builtin.lineinfile:
    path: "{{ dotfiles_directory_path }}/zsh/aliases.zsh"
    line: alias grep='rg'
    insertbefore: "^{{ custom_config_end_delimiter }}"
    state: present
  become: false
  tags: unix
