---
- name: Ensure destination directory exists
  ansible.builtin.file:
    path: "{{ dotfiles_directory_path }}/git"
    state: directory
    mode: "0755"
  become: false
  tags: unix

- name: Link directory from role files to local destination
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ dotfiles_directory_path }}/git"
    state: link
    mode: "0755"
    force: true
    follow: false
  become: false
  tags: unix

- name: Set commit.template
  community.general.git_config:
    name: commit.template
    scope: global
    value: "{{ dotfiles_directory_path }}/git/commit.template"
  become: false
  tags: unix

- name: Set global .gitignore
  community.general.git_config:
    name: core.excludesFile
    value: "{{ dotfiles_directory_path }}/git/gitignore"
    scope: global
  become: false
  tags: unix

- name: Set init.defaultBranch
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main
  become: false
  tags: unix

- name: Set editor
  community.general.git_config:
    name: core.editor
    value: "hx"
    scope: global
  become: false
  tags: unix

- name: Set precomposeunicode
  community.general.git_config:
    name: core.precomposeunicode
    value: true
    scope: global
  become: false
  when: ansible_os_family == "Darwin"
  tags: unix

- name: Set diff.colorMoved
  community.general.git_config:
    name: diff.colorMoved
    scope: global
    value: zebra
  become: false
  tags: unix

- name: Set fetch.prune
  community.general.git_config:
    name: fetch.prune
    scope: global
    value: true
  become: false
  tags: unix

- name: Set pull.rebase
  community.general.git_config:
    name: pull.rebase
    scope: global
    value: true
  become: false
  tags: unix

- name: Set pull.ff
  community.general.git_config:
    name: pull.ff
    scope: global
    value: "only"
  become: false
  tags: unix

- name: Set rebase.autoStash
  community.general.git_config:
    name: rebase.autoStash
    scope: global
    value: true
  become: false
  tags: unix

- name: Set up Git aliases
  community.general.git_config:
    name: "alias.{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { name: a, value: add }
    - { name: b, value: branch }
    - { name: ba, value: branch --all }
    - { name: bd, value: branch -D }
    - { name: c, value: commit }
    - { name: ca, value: commit -a }
    - { name: cm, value: commit -m }
    - { name: cam, value: commit -am }
    - { name: d, value: diff -w }
    - { name: dst, value: diff -w --staged }
    - { name: dc, value: diff -w --cached }
    - { name: st, value: status }
    - { name: rba, value: rebase --abort }
    - { name: rbc, value: rebase --continue }
  become: false
  tags: unix

- name: Ensure .config/git directory exists
  ansible.builtin.file:
    path: "{{ dotfiles_directory_path }}/git"
    state: directory
    mode: "0755"
  become: false
  tags: unix

- name: Set user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ github_name }}"
  become: false
  tags: unix

- name: Set user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ github_email }}"
  become: false
  tags: unix

- name: Set tag.gpgsign
  community.general.git_config:
    name: tag.gpgsign
    scope: global
    value: true
  become: false
  tags: unix

- name: Set commit.gpgsign
  community.general.git_config:
    name: commit.gpgsign
    scope: global
    value: true
  become: false
  tags: unix

- name: Set gpg.program
  community.general.git_config:
    name: gpg.program
    scope: global
    value: "gpg"
  become: false
  tags: unix

- name: Set user.signingkey
  community.general.git_config:
    name: user.signingkey
    scope: global
    value: "{{ gpg_signing_key }}"
  become: false
  tags: unix
