---
- name: Ensure git in macOS
  ansible.builtin.include_tasks: macos.yml
  tags: macos

- name: Configure git
  ansible.builtin.include_tasks: config.yml
  tags: unix

- name: Configure SSH for git
  ansible.builtin.include_tasks: ssh.yml
  tags: unix
