---
- name: Check if Java plugin is already added
  ansible.builtin.command: asdf plugin list
  register: plugin_list
  changed_when: false
  failed_when: false
  become: false
  tags: unix

- name: Add Java plugin if not already added
  ansible.builtin.command: asdf plugin-add java https://github.com/halcyon/asdf-java.git
  when: "'java' not in plugin_list.stdout"
  register: plugin_added
  changed_when: plugin_added.rc == 0
  become: false
  tags: unix

- name: Check if Java is already installed
  ansible.builtin.command: asdf list java
  register: java_list
  failed_when: false
  changed_when: false
  tags: unix

- name: Install 21 version of Java if not already installed
  ansible.builtin.command: asdf install java temurin-21.0.2+13.0.LTS
  when: "'temurin-21.0.2+13.0.LTS' not in java_list.stdout"
  register: java_install
  failed_when: "'already installed' not in java_install.stdout and java_install.rc != 0"
  changed_when: java_install.rc == 0
  tags: unix

- name: Set global Java version
  ansible.builtin.command: asdf global java {{ java_latest.stdout }}
  when: "'temurin-21.0.2+13.0.LTS' not in java_list.stdout"
  changed_when: java_install.changed
  become: false
  tags: unix
