---
- name: Configure system settings in macOS
  ansible.builtin.include_tasks: macos/main.yml
  when: ansible_os_family == "Darwin"
  tags: macos

- name: Configure system settings in macOS
  ansible.builtin.include_tasks: debian/main.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags: debian
