---
- name: Ensure zsh is installed
  community.general.homebrew:
    name: zsh
    state: present
  become: false
  tags: macos

- name: Change admin default shell to zsh
  ansible.builtin.shell: chsh -s $(which zsh)
  become: true
  changed_when: false
  tags: macos

- name: Change user default shell to zsh
  ansible.builtin.shell: chsh -s $(which zsh) $(whoami)
  become: true
  changed_when: false
  tags: macos

- name: Ensure .zshrc exists
  ansible.builtin.file:
    path: "{{ home_path }}/.zshrc"
    state: touch
    mode: "0644"
  tags: unix

- name: Ensure .zshrc includes Homebrew path for Apple Silicon-based machine
  ansible.builtin.blockinfile:
    path: "{{ home_path }}/.zshrc"
    block: "export PATH=/opt/homebrew/bin:$PATH"
    state: present
    insertafter: "^{{ custom_config_start_delimiter }}"
    mode: "0644"
    marker: "# --- {mark} Homebrew ---"
  become: false
  notify: Reload shell
  when:
    - ansible_os_family == "Darwin"
  tags: macos
