---
- name: Ensure zsh is installed on Debian-based systems
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Ensure zsh is the default shell for the user
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/bin/zsh
