---
- name: Ensure zsh is installed on Debian-based systems
  ansible.builtin.apt:
    name: zsh
    state: present
  become: true
  tags: debian

- name: Change admin default shell to zsh
  ansible.builtin.shell: chsh -s $(which zsh)
  become: true
  changed_when: false
  tags: debian

- name: Change user default shell to zsh
  ansible.builtin.shell: chsh -s $(which zsh) {{ ansible_user }}
  become: true
  changed_when: false
  tags: debian
