---
- name: Set up flutter to install
  ansible.builtin.command: asdf plugin-add flutter
  when: asdf_check.rc == 0
  register: plugin_added
  changed_when: plugin_added.rc == 0

- name: Install latest version of Flutter
  ansible.builtin.command: asdf install flutter {{ latest_version }}
  when: asdf_check.rc == 0
  register: flutter_install
  changed_when: flutter_install.rc == 0

- name: Set global Flutter version
  ansible.builtin.command: asdf global flutter {{ latest_version }}
  when: asdf_check.rc == 0
  changed_when: flutter_install.changed
  notify: Reload shell

- name: Check installed Flutter version
  ansible.builtin.command: asdf current flutter
  register: current_flutter
  changed_when: false

- name: Ensure Flutter is the latest version
  ansible.builtin.command: asdf install flutter {{ latest_version }}
  when: current_flutter.stdout != latest_version
  register: flutter_update
  changed_when: flutter_update.rc == 0

- name: Accept Flutter licenses
  ansible.builtin.command: echo "y" | flutter doctor --android-licenses
