---
- name: Ensure asdf in macOS
  community.general.homebrew:
    state: present
    name:
      - coreutils
      - curl
      - git
      - asdf
  become: false
  tags: macos

- name: Ensure .zshrc includes asdf initialization
  ansible.builtin.blockinfile:
    path: "{{ home_path }}/.zshrc"
    block: ". /opt/homebrew/opt/asdf/libexec/asdf.sh"
    state: present
    mode: "0644"
    insertbefore: "^{{ custom_config_end_delimiter }}"
    marker: "# --- {mark} asdf ---"
  become: false
  notify: Reload shell
  when:
    - ansible_facts['pkg_mgr'] == "homebrew" # Ensures Homebrew is the package manager
    - ansible_os_family == "Darwin"
  tags: macos
