---
- name: Ensure asdf in macOS
  community.general.homebrew:
    state: present
    name:
      - coreutils
      - curl
      - git
      - asdf
  become: false
  tags: dev, macos

- name: Ensure .zshrc includes asdf initialization
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    line: ". /opt/homebrew/opt/asdf/libexec/asdf.sh"
    state: present
    create: yes
    mode: "0644"
    insertbefore: "^{{ custom_config_end_delimiter }}"
  become: false
  notify: Reload shell
  when:
    - ansible_facts['pkg_mgr'] == "homebrew" # Ensures Homebrew is the package manager
    - ansible_os_family == "Darwin"
  tags: dev, macos
