- name: "Install asdf plugins"
  shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf plugin-add {{ item }} || exit 0
  with_items:
    - direnv
    - flutter
    - java
    - kotlin
    - nodejs
    - rust

- name: "Install Default Direnv"
  shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf install direnv latest
    asdf global direnv latest

- name: "Install Default Flutter"
  shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf install flutter latest
    asdf global flutter latest

- name: "Install Default Kotlin"
  shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf install kotlin latest
    asdf global kotlin latest

- name: "Install Default Java"
  shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf install java temurin-jre-21.0.2+13.0.LTS
    asdf global java temurin-jre-21.0.2+13.0.LTS

- name: "Install Default Node.js"
  shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf install nodejs lts
    asdf global nodejs lts

- name: "Install Default Rust"
  shell: |
    source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
    asdf install rust latest
    asdf global rust latest
