- name: Install homebrew
  include_role:
    name: geerlingguy.mac.homebrew

- name: Make sure homebrew bin is in path
  ansible.builtin.lineinfile:
    path: /etc/paths
    state: present
    line: '/opt/homebrew/bin'
  become: true
  become_user: root

- name: 'add custom homebrew repos'
  community.general.homebrew_tap:
    name: [
      fishtown-analytics/dbt,
      homebrew/cask-versions,
    ]

- name: Install core packages via brew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
  ignore_errors: true
  with_items:
    - android-sdk
    - android-studio
    - docker
    - figma
    - google-chrome
    - visual-studio-code

- name: "Install homebrew packages"
  community.general.homebrew:
    name: [
      'asdf',
      'curl',
      'fzf',
      'gpg',
      'htop',
      'mas',
      'openssl' ,
      'tmux',
      'unzip',
      'helix',
      'watchman',
      'zsh',
    ]
    state: present
    update_homebrew: true

- name: "Install from Mac app store"
  shell: mas install {{ item }}
  with_items:
    - 497799835 # xcode