---
- name: Ensure Docker in debian
  ansible.builtin.include_tasks: debian/install.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags: debian

- name: Ensure Docker in macOS
  ansible.builtin.include_tasks: macos/install.yml
  when: ansible_os_family == "Darwin"
  tags: macos
