---
- name: Ensure starship in macOS
  ansible.builtin.include_tasks: macos/install.yml
  when: ansible_os_family == "Darwin"
  tags: macos

- name: Ensure starship in debian
  ansible.builtin.include_tasks: debian/install.yml
  when: ansible_os_family == "Debian"
  tags: debian

- name: Link config file from role files to local destination when local
  ansible.builtin.file:
    src: "{{ role_path }}/files/config.toml"
    dest: "{{ dotfiles_directory_path }}/starship.toml"
    state: link
    mode: "0644"
    force: true
    follow: false
  when: is_local_connection
  become: false
  tags: unix

- name: Copy config file from role files to local destination when local
  ansible.builtin.copy:
    src: "{{ role_path }}/files/config.toml"
    dest: "{{ dotfiles_directory_path }}/starship.toml"
    mode: "0644"
    force: true
  when: not is_local_connection
  become: false
  tags: unix

- name: Add Starship init line to .zshrc if Starship is installed
  ansible.builtin.blockinfile:
    path: "{{ home_path }}/.zshrc"
    block: 'eval "$(starship init zsh)"'
    insertbefore: "^{{ custom_config_end_delimiter }}"
    marker: "# --- {mark} starship ---"
    state: present
  tags: unix
