---
- name: Ensure starship in macOS
  ansible.builtin.include_tasks: macos.yml
  when: ansible_os_family == "Darwin"
  tags: dev, macos

- name: Link config file from role files to local destination
  ansible.builtin.file:
    src: "{{ role_path }}/files/config.toml"
    dest: "{{ dotfiles_directory_path }}/starship.toml"
    state: link
    mode: "0644"
    force: true
    follow: false
  become: false
  tags: unix

- name: Add Starship init line to .zshrc if Starship is installed
  ansible.builtin.blockinfile:
    path: "{{ home_path }}/.zshrc"
    block: 'eval "$(starship init zsh)"'
    insertbefore: "^{{ custom_config_end_delimiter }}"
    marker: "# --- {mark} starship ---"
    state: present
  notify: Reload shell
  tags: unix
