---
- name: Ensure starship in macOS
  ansible.builtin.include_tasks: macos.yml
  when: ansible_os_family == "Darwin"
  tags: macos

- name: Link config file from role files to local destination
  ansible.builtin.file:
    src: "{{ role_path }}/files/config.toml"
    dest: "{{ lookup('env', 'HOME') }}/.config/starship.toml"
    state: link
    mode: 0644
    force: true
    follow: false
  become: false
  tags: unix

- name: Add Starship init line to .zshrc if Starship is installed
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    line: 'eval "$(starship init zsh)" # starship'
    insertbefore: "^{{ custom_config_end_delimiter }}"
    state: present
  notify: Reload shell
  tags: unix
