---
- name: Ensure Alacritty in macOS
  ansible.builtin.include_tasks: macos.yml
  when: ansible_os_family == "Darwin"
  tags: macos

- name: Ensure destination directory exists
  ansible.builtin.file:
    path: "{{ dotfiles_directory_path }}/alacritty"
    state: directory
    mode: "0755"
  become: false
  tags: unix

- name: Link file from role files to local destination
  ansible.builtin.file:
    src: "{{ role_path }}/files/config.toml"
    dest: "{{ dotfiles_directory_path }}/alacritty/alacritty.toml"
    state: link
    mode: "0644"
    force: true
    follow: false
  become: false
  tags: unix
