---
- name: Ensure gpg is installed
  community.general.homebrew:
    state: present
    name: gpg
  become: false
  tags: dev, macos

- name: Add GPG line to .zshrc if GPG is installed
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    line: "export GPG_TTY=$(tty) # GPG setup"
    insertbefore: "^{{ custom_config_end_delimiter }}"
    state: present
  notify: Reload shell
  tags: dev, macos
