---
- name: Ensure gpg is installed
  community.general.homebrew:
    state: present
    name: gpg
  become: false
  tags: macos

- name: Ensure .zshrc exists
  ansible.builtin.file:
    path: "{{ home_path }}/.zshrc"
    state: touch
    mode: "0644"
  tags: unix

- name: Add GPG line to .zshrc if GPG is installed
  ansible.builtin.blockinfile:
    path: "{{ home_path }}/.zshrc"
    block: "export GPG_TTY=$(tty)"
    insertbefore: "^{{ custom_config_end_delimiter }}"
    state: present
    marker: "# --- {mark} gpg ---"
  notify: Reload shell
  tags: macos
