---
- name: Set OS-specific variables
  ansible.builtin.set_fact:
    docker_host_env: "{{ os_config[ansible_system].docker_host_env }}"
    homeassistant_directory: "{{ os_config[ansible_system].common_directory }}/homeassistant"
    become_enabled: "{{ os_config[ansible_system].become_enabled }}"
  vars:
    os_config:
      Darwin:
        docker_host_env: "unix:///Users/{{ ansible_user_id }}/.colima/default/docker.sock"
        common_directory: "{{ ansible_user_dir }}/Library/Application Support"
        become_enabled: false
      Linux:
        docker_host_env: "unix:///var/run/docker.sock"
        common_directory: "/mnt/shared"
        become_enabled: true
  tags: unix

- name: Ensure zigbee2mqtt setup completed
  ansible.builtin.include_role:
    name: z2m
  tags: unix

- name: Ensure Docker exists
  ansible.builtin.include_role:
    name: docker
  tags: unix

- name: Ensure Home Assistant directories exist
  ansible.builtin.file:
    path: "{{ item }}" # Iterates through the list of paths
    state: directory
    mode: '0755'
  loop:
    - "{{ homeassistant_directory }}"
    - "{{ homeassistant_directory }}/config"
  become: "{{ become_enabled }}"
  tags: unix

- name: Ensure Home Assistant Docker container is running and configured
  community.docker.docker_container:
    name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    state: started
    privileged: true
    restart_policy: unless-stopped
    ports:
      - "18123:8123"
    volumes:
      - "{{ homeassistant_directory }}/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/run/dbus:/run/dbus:ro"
    env:
      TZ: "{{ timezone }}"
  become: "{{ become_enabled }}"
  environment:
    DOCKER_HOST: "{{ docker_host_env }}"
  tags: unix
