---
- name: Add helix PPA
  ansible.builtin.apt_repository:
    repo: ppa:maveonair/helix-editor
    update_cache: yes
  become: true
  tags: debian

- name: Install helix
  ansible.builtin.apt:
    name: helix
    state: present
  become: true
  tags: debian
