---
- name: Create screenshots directory
  ansible.builtin.file:
    path: "{{ screenshot_dir_path }}"
    state: directory
  become: false

- name: Set Screenshot settings
  community.general.osx_defaults:
    domain: com.apple.screencapture
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    # Set screenshot location
    - { key: "location", type: "string", value: "{{ screenshot_dir_path }}" }
    # Save screenshots in PNG format
    #  - Other options BMP, GIF, JPG, PDF, TIFF
    - { key: "type", type: "string", value: "png" }
  become: false
  tags: osx, screenshot
