---
- name: Disable the sound effects on boot
  ansible.builtin.shell: nvram SystemAudioVolume=" "
  become: true
  changed_when: false

- name: Enable HiDPI display modes (requires restart)
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.windowserver
    key: DisplayResolutionEnabled
    type: bool
    value: true
    state: present
  become: true

- name: Disable the "Are you sure you want to open this application?"" dialog
  community.general.osx_defaults:
    domain: com.apple.LaunchServices
    key: LSQuarantine
    type: bool
    value: false
  become: false
