---
- name: Ensure ASDF in macOS
  community.general.homebrew:
    state: present
    name:
      - coreutils
      - curl
      - git
      - asdf
  become: false
  tags: macos

- name: Ensure .zshrc includes asdf initialization
  ansible.builtin.lineinfile:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    line: ". /opt/homebrew/opt/asdf/libexec/asdf.sh"
    state: present
    create: yes
    insertbefore: "^{{ custom_config_end_delimiter }}"
  become: false
  tags: macos
  when:
    - ansible_facts['pkg_mgr'] == "homebrew" # Ensures Homebrew is the package manager
    - ansible_os_family == "Darwin"

- name: Enable Rosetta for GUI application
  ansible.builtin.command: echo "a" |  softwareupdate --install-rosetta
  register: rosetta_install
  changed_when: rosetta_install.rc != 0
  become: false
  tags: macos
